[theme]
# üéÑ CHARTE GRAPHIQUE NO√ãL üéÑ

# Couleur principale (Boutons, Sliders, S√©lection) -> Rouge P√®re No√´l
primaryColor = "#D42426"

# Couleur de fond (Background) -> Blanc Neige (l√©g√®rement cass√© pour les yeux)
backgroundColor = "#FDFDFD"

# Couleur de fond secondaire (Sidebar, Cartes) -> Vert Sapin tr√®s clair ou Blanc cass√©
secondaryBackgroundColor = "#F0F7F4"

# Couleur du texte -> Gris anthracite (plus doux que le noir pur)
textColor = "#2C3E50"

# Police d'√©criture (Optionnel, sans-serif fait plus moderne)
font = "sans serif"

[server]
# D√©sactive la barre de d√©veloppement en haut
headless = true